[global]
overload_tap_timeout = 500

[ids]
*

[visual]

[main]
capslock = overload(vim, esc)
escape = capslock

leftmeta = overload(meta, compose)
f23+leftshift+leftmeta = overload(meta, compose)

compose = overload(meta, compose)

[vim]
h = left
j = down
k = up
l = right

e = C-right
b = C-left

0 = home
4 = end

u = pageup
d = pagedown

[ = C-home
] = C-end

x = C-x
c = C-c
v = C-v
z = C-z
r = C-S-z

a = C-a
backspace = C-backspace

space = toggle(visual)

[vim+visual]
h = S-left
j = S-down
k = S-up
l = S-right

e = C-S-right
b = C-S-left

0 = S-home
4 = S-end

u = S-pageup
d = S-pagedown

[ = C-S-home
] = C-S-end

x = C-x
c = C-c
v = C-v
z = C-z
r = C-S-z

a = C-a
backspace = C-backspace
