require('which-key').setup {
    preset = 'helix',
    delay = 0,
    icons = {
        mappings = false,
        keys = {
            Up = 'Up',
            Down = 'Down',
            Left = 'Left',
            Right = 'Right',
            C = 'C-',
            M = 'M-',
            D = 'D-',
            S = 'S-',
            CR = 'CR',
            Esc = 'Esc',
            ScrollWheelDown = 'ScrollDown',
            ScrollWheelUp = 'ScrollUp',
            NL = 'NL',
            BS = 'BS',
            Space = 'SPC',
            Tab = 'Tab',
            F1 = 'F1',
            F2 = 'F2',
            F3 = 'F3',
            F4 = 'F4',
            F5 = 'F5',
            F6 = 'F6',
            F7 = 'F7',
            F8 = 'F8',
            F9 = 'F9',
            F10 = 'F10',
            F11 = 'F11',
            F12 = 'F12',
        },
    },
    win = {
        border = 'single',
        no_overlap = false,
        padding = { 1, 2 },
    },
    plugins = {
        marks = false,
        registers = false,
    },
    keys = {
        scroll_up = '<c-p>',
        scroll_down = '<c-n>',
    },
    spec = {
        { '<leader>g', group = 'Git',   mode = { 'n', 'v' } },
        { '<leader>s', group = 'Search' },
        { '<leader>t', group = 'Tabs' },
        { '<leader>D', group = 'Debug' },
    },
}
