set -sa terminal-overrides ",xterm*:Tc"
set -g mouse on
set -s extended-keys on
set -g default-terminal "tmux-256color"
set -g escape-time 0

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g history-limit 50000
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on
set -g aggressive-resize on

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind \; split-window -v -c "#{pane_current_path}"
bind "'" split-window -h -c "#{pane_current_path}"

bind-key x kill-pane
bind-key & kill-window
bind z resize-pane -Z

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

bind -n C-M-h resize-pane -L 2
bind -n C-M-j resize-pane -D 2
bind -n C-M-k resize-pane -U 2
bind -n C-M-l resize-pane -R 2

set -g pane-border-style "fg=#555555 bg=default"
set -g pane-active-border-style "fg=#00afff bg=#1c1c1c"
set -g mode-style "fg=white,bg=#282828"
set -g status-bg "#282828"
set -g status-fg white
set -g status-justify left
set -g status-left ' '
set -g status-left-length 0
set -g status-right '#{?client_prefix,[PREFIX] ,}#S '
set -g status-right-length 40
set -g status-position bottom

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

run '~/.config/tmux/plugins/tpm/tpm'
