[mgr]
prepend_keymap = [
  # Plugins
  { on = ["g", "l"], run = "plugin lazygit", desc = "Open LazyGit" },
  { on = "C", run = "plugin ouch", desc = "Open ouch menu" },
  { on = ["c", "m"], run = "plugin chmod", desc = "Chmod on selected files" },
  { on = "z", run = "plugin fzf", desc = "Jump via fzf" },
  { on = "Z", run = "plugin zoxide", desc = "Jump via zoxide" },
  { on = "O", run = "plugin open-with-cmd", desc = "Open with command" },

  # Custom directory jumps
  { on = ["g", "c"], run = "cd ~/.config", desc = "Go ~/.config" },
  { on = ["g", "D"], run = "cd ~/Downloads", desc = "Go ~/Downloads" },
  { on = ["g", "d"], run = "cd ~/dots", desc = "Go ~/dots" },
]
