[mgr]
scrolloff = 200
show_hidden = false
show_symlink = true

[preview]
image_provider = "sixel"
sixel_fraction = 15
max_width = 1920
max_height = 1200
wrap = "yes"
image_filter = "lanczos3"

[plugin]
prepend_previewers = [
  { mime = "audio/*", run = "mediainfo" },
  { mime = "video/*", run = "mediainfo" },
]
