# ~/.config/fuzzel/fuzzel.ini

[main]
font=Iosevka Nerd Font:size=9
dpi-aware=auto
icon-theme=Papirus-Dark
letter-spacing=1
fields=name,generic,comment,categories,filename,keywords
terminal=$TERMINAL -e 
width=40
horizontal-pad=12
line-height=14
lines=12

[border]
width=1
radius=0

[colors]
background=282928ff
text=ffffffff
input=ffffffff
prompt=ffffffff
placeholder=8b8f93ff
border=d3d7cfff
match=00afffff

# Changed selection background to white
selection=ffffffff

# Changed selection text color to black
selection-text=000000ff

# Kept this the same; it will be dark grey on the white background
selection-match=282928ff

[dmenu]
mode=text
exit-immediately-if-empty=yes

[key-bindings]
# Unmap default 'delete-line-forward' (Ctrl+k) to free it up
delete-line-forward=none

# Vim-style navigation
prev=Up Control+p Control+k
next=Down Control+n Control+j
