monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_input.pci.*analog-stereo"
      }
    ]
    actions = {
      update-props = {
        node.lock-volume = true
      }
    }
  }
]
