[general]
fullscreen = true
floating-hack = true
initial-tool = "arrow"
early-exit = true
early-exit-save-as = true
corner-roundness = 12
copy-command = "wl-copy"
annotation-size-factor = 1
save-after-copy = false
default-hide-toolbars = false
output-filename = "/home/r3d/Pictures/Screenshots/Screenshot_%Y-%m-%d_%H:%M:%S.png"
focus-toggles-toolbars = false
default-fill-shapes = false
primary-highlighter = "block"
disable-notifications = true
actions-on-right-click = []
actions-on-enter = ["save-to-clipboard", "exit"]
actions-on-escape = ["exit"]
no-window-decoration = true
brush-smooth-history-size = 0
pan-step-size = 50.0
zoom-factor = 1.1
text-move-length = 50.0
input-scale = 2.0

# Tool selection keyboard shortcuts
[keybinds]
pointer = "p"
crop = "c"
brush = "d"
line = "l"
arrow = "a"
rectangle = "r"
ellipse = "e"
text = "t"
marker = "m"
blur = "b"
highlight = "h"

# Font to use for text annotations
[font]
family = "Roboto"
style = "Regular"
fallback = [
  "Noto Sans CJK JP",
  "Noto Sans CJK SC",
  "Noto Sans CJK TC",
  "Noto Sans CJK KR",
  "Noto Serif CJK JP",
  "Noto Serif JP",
  "IPAGothic",
  "IPAexGothic",
  "Source Han Sans",
]

# Custom colours for the colour palette
[color-palette]
palette = ["#00ffff", "#a52a2a", "#dc143c", "#ff1493", "#ffd700", "#008000"]

custom = ["#00ffff", "#a52a2a", "#dc143c", "#ff1493", "#ffd700", "#008000"]
