[general]
fullscreen = false
floating-hack = true
resize = { mode = "smart" }
corner-roundness = 10
annotation-size-factor = 1
brush-smooth-history-size = 4
default-round-caps = true
initial-tool = "arrow"
copy-command = "wl-copy"
output-filename = "~/Pictures/Screenshots/Screenshot_%Y-%m-%d_%H:%M:%S.png"
disable-notifications = true
actions-on-enter = ["save-to-clipboard", "save-to-file", "exit"]
actions-on-escape = ["exit"]
no-window-decoration = false

[keybinds]
pointer = "p"
crop = "c"
brush = "d"
line = "l"
arrow = "a"
rectangle = "r"
ellipse = "e"
text = "t"
marker = "m"
blur = "b"
highlight = "h"

[font]
family = "Roboto"
style = "Regular"
fallback = [
  "Noto Sans CJK JP",
  "Noto Sans CJK SC",
  "Noto Sans CJK TC",
  "Noto Sans CJK KR",
  "Noto Serif CJK JP",
  "Noto Serif JP",
  "IPAGothic",
  "IPAexGothic",
  "Source Han Sans",
]

[color-palette]
palette = ["#00ffff", "#a52a2a", "#dc143c", "#ff1493", "#ffd700", "#008000"]
custom = ["#00ffff", "#a52a2a", "#dc143c", "#ff1493", "#ffd700", "#008000"]
