background            #000000
# foreground            #f1f1f1
# foreground            #b0b0b0
foreground            #c0c0c0

cursor                #7f7f7f
selection_background  #b4d5ff
color0                #4f4f4f
color8                #7b7b7b
color1                #cb584d   
color9                #d9928a   
color2                #8ec06e   
color10               #aed990   
color3                #c7b667   
color11               #d9c882   
color4                #7b9cc0   
color12               #9bb8d2   
color5                #c66acb   
color13               #d390d4   
color6                #a3a2d0   
color14               #b8b7e0   
color7                #c0c0c0   
color15               #d0d0d0   
selection_foreground  #000000

# cursor                #7f7f7f
# selection_background  #b4d5ff
# color0                #4f4f4f
# color8                #7b7b7b
# color1                #fa6c5f
# color9                #fcb6af
# color2                #a8fe60
# color10               #ceffab
# color3                #fffeb6
# color11               #fffecc
# color4                #96cafd
# color12               #b5dcfe
# color5                #fa72fc
# color13               #fb9bfe
# color6                #c6c4fd
# color14               #dfdffd
# color7                #eeedee
# color15               #fefffe
# selection_foreground #000000

# tab_bar_background      #181a1f
tab_bar_background      #000000
tab_bar_margin_color    #181a1f
active_tab_foreground   #abb2bf
active_tab_background   #232634
inactive_tab_foreground #5c6370
inactive_tab_background #181a1f
