prepend-previewers = [
  { url = "*.md", run = "glow" },
  { mime = "audio/*", run = "mediainfo" },
  { mime = "video/*", run = "mediainfo" },
]

[preview]
image_provider = "sixel"
sixel_fraction = 15
max_width = 1920
max_height = 1200

[opener]
edit = [{ run = 'nvim "$@"', block = true, desc = "Edit" }]
