gui:
  theme:
    defaultFgColor:
      - default
      - default
    activeBorderColor:
      - cyan
      - bold
    inactiveBorderColor:
      - default
    searchingActiveBorderColor:
      - magenta
      - bold
    selectedLineBgColor:
      - reverse
    inactiveViewSelectedLineBgColor:
      - default
    unstagedChangesColor:
      - red
    optionsTextColor:
      - blue
    cherryPickedCommitBgColor:
      - cyan
    cherryPickedCommitFgColor:
      - black
    markedBaseCommitBgColor:
      - yellow
    markedBaseCommitFgColor:
      - black
