context.modules = [
{   name = libpipewire-module-filter-chain
    args = {
        node.description = "Dolby Atmos IEM Sink"
        media.name       = "Dolby Atmos IEM Sink"
        filter.graph = {
            nodes = [
                {
                    type   = builtin
                    name   = eq
                    label  = param_eq
                    config = {
                        filters = [
                            { type = bq_peaking freq = 32.0    q = 1.5047602 gain = 4.0  }
                            { type = bq_peaking freq = 64.0    q = 1.5047602 gain = 2.0  }
                            { type = bq_peaking freq = 125.0   q = 1.5047602 gain = 1.0  }
                            { type = bq_peaking freq = 500.0   q = 1.5047602 gain = -1.0 }
                            { type = bq_peaking freq = 1000.0  q = 1.5047602 gain = -2.0 }
                            { type = bq_peaking freq = 4000.0  q = 1.5047602 gain = 2.0  }
                            { type = bq_peaking freq = 8000.0  q = 1.5047602 gain = 3.0  }
                            { type = bq_peaking freq = 16000.0 q = 1.5047602 gain = 3.0  }
                        ]
                    }
                }
                {
                    type   = builtin
                    name   = conv_l
                    label  = convolver
                    config = {
                        filename = "/etc/pipewire/Dolby_Atmos_Default.irs"
                        channel  = 0
                        gain     = 0.630957
                    }
                }
                {
                    type   = builtin
                    name   = conv_r
                    label  = convolver
                    config = {
                        filename = "/etc/pipewire/Dolby_Atmos_Default.irs"
                        channel  = 1
                        gain     = 0.630957
                    }
                }
            ]
            links = [
                { output = "eq:Out 1" input = "conv_l:In" }
                { output = "eq:Out 2" input = "conv_r:In" }
            ]
            inputs  = [ "eq:In 1" "eq:In 2" ]
            outputs = [ "conv_l:Out" "conv_r:Out" ]
        }
        audio.position = [ FL FR ]
        capture.props = {
            media.class      = "Audio/Sink"
            node.name        = "dolby_iem_sink"
            priority.driver  = 2000
            priority.session = 2000
        }
        playback.props = {
            node.name    = "playback.dolby_iem_sink"
            node.passive = true
        }
    }
}
]
