context.modules = [
{   name = libpipewire-module-filter-chain
    args = {
        node.description = "Noise Canceling Microphone"
        media.name       = "Noise Canceling Microphone"
        filter.graph = {
            nodes = [
                {
                    type    = builtin
                    name    = hp
                    label   = bq_highpass
                    control = { "Freq" = 90.0 "Q" = 0.707 }
                }
                {
                    type    = ladspa
                    name    = rnnoise
                    plugin  = /usr/lib/ladspa/librnnoise_ladspa.so
                    label   = noise_suppressor_mono
                    control = {
                        "VAD Threshold (%)"         = 20.0
                        "VAD Grace Period (ms)"      = 600
                        "Retroactive VAD Grace (ms)" = 50
                    }
                }
                {
                    type    = ladspa
                    name    = limiter
                    plugin  = /usr/lib/ladspa/fast_lookahead_limiter_1913.so
                    label   = fastLookaheadLimiter
                    control = {
                        "Input gain (dB)"  = 10.0
                        "Limit (dB)"       = -1.0
                        "Release time (s)" = 0.1
                    }
                }
            ]
            links = [
                { output = "hp:Out"         input = "rnnoise:Input" }
                { output = "rnnoise:Output" input = "limiter:Input 1" }
            ]
            inputs  = [ "hp:In" ]
            outputs = [ "limiter:Output 1" ]
        }
        audio.position = [ MONO ]
        capture.props = {
            node.name      = "capture.rnnoise_source"
            node.passive   = true
            audio.position = [ MONO ]
        }
        playback.props = {
            node.name        = "rnnoise_source"
            media.class      = "Audio/Source"
            priority.driver  = 2000
            priority.session = 2000
            audio.position   = [ MONO ]
        }
    }
}
]
